spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        generate_statistics: true
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB